# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-16 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etiqueta',
            old_name='Produto',
            new_name='produto',
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
