# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-18 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produtos', '0004_produto_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiqueta',
            name='produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='produto_logo',
            new_name='imagem',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.AddField(
            model_name='produto',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
    ]
