# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-21 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_auto_20180318_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='valor',
        ),
    ]
